### ISSUE TITLE
No Button on YouTube.com's new Player

### ISSUE THREAD

**Issue by tbeseda** [maxogden/playback-chrome#2]
I think YouTube's new player is throwing off Playback's button. You can see the lack of a button in this screenshot:

![the_new_3d_robotics_solo_may_be_the_smartest_drone_yet_-_youtube_2015-04-13_10-24-06](https://cloud.githubusercontent.com/assets/15697/7120032/692aad98-e1c7-11e4-96c3-57689682069a.jpg)

Here's a relevant error from the console:

![developer_tools_-_httpswww youtube comwatchvmpl1hbtxfhe_2015-04-13_10-23-08](https://cloud.githubusercontent.com/assets/15697/7120041/72b95512-e1c7-11e4-841d-ac0bd767fb42.jpg)

**Comment by max-mapper** [comment]
lemme know if the fix doesnt work. should be out in the web store in an hour or two (publishing is slow), or you can load unpacked extension from a built copy of this repo

**Comment by tbeseda** [comment]
Looks good!
